
trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Hello Bindu.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
